CREATE TABLE USERS
(
    USERNAME VARCHAR(255) CONSTRAINT PK_TABLE_USERS PRIMARY KEY,
    PASSWORD VARCHAR(255) NOT NULL,
    CONSTRAINT UNIQUE_USERNAME_TABLE_USERS UNIQUE (USERNAME)
);

CREATE TABLE ROLES
(
    NAME VARCHAR(255) CONSTRAINT PK_TABLE_ROLES PRIMARY KEY,
    CONSTRAINT UNIQUE_NAME_TABLE_ROLES UNIQUE (NAME)
);

CREATE TABLE USERS_ROLES
(
    ACCOUNT_CREDENTIALS_USERNAME VARCHAR(255) CONSTRAINT PK_USERS_ROLES,
    ROLES_NAME VARCHAR(255) CONSTRAINT PK_USERS_ROLES,
    CONSTRAINT PK_TABLE_USERS_ROLES PRIMARY KEY(ACCOUNT_CREDENTIALS_USERNAME, ROLES_NAME)
);