INSERT INTO USERS VALUES ('admin', '$2a$10$UYhzrR1gNyad6KRsjN9oaOR6WXjZuY7vwDmie0WNG.NyOHM0U00Am'); -- Senha do admin é admin
INSERT INTO USERS VALUES ('teacher', '$2y$12$8bWKa/sP0.0L7UqGdLDELeXaTr0N9PCmJW4NroOCoxro.3NPa93hu'); -- Senha do teacher é teacher
INSERT INTO USERS VALUES ('student', '$2y$12$TdnK3azyQ7ijZUHWx/5pL.BJBb2lFJ4YZC5yxmh0THdI/W8OoOrCS'); -- Senha do student é student

INSERT INTO ROLES VALUES('ADMIN');
INSERT INTO ROLES VALUES('TEACHER');
INSERT INTO ROLES VALUES('STUDENT');

INSERT INTO USERS_ROLES VALUES('admin', 'ADMIN');
INSERT INTO USERS_ROLES VALUES('teacher', 'TEACHER');
INSERT INTO USERS_ROLES VALUES('student', 'STUDENT');

INSERT INTO STUDENTS VALUES('1', '111.222.333.44', 'Estudante-1');
INSERT INTO STUDENTS VALUES('2', '111.222.333.45', 'Estudante-3');
INSERT INTO STUDENTS VALUES('3', '111.222.333.46', 'Estudante-3');

INSERT INTO TEACHERS VALUES('1', '111.222.333.11', 'Professor-1');
INSERT INTO TEACHERS VALUES('2', '111.222.333.22', 'Professor-3');
INSERT INTO TEACHERS VALUES('3', '111.222.333.33', 'Professor-3');

INSERT INTO CLASSES VALUES('Seguranca e Auditoria', '2021/1', '1');

INSERT INTO CLASSES_STUDENTS VALUES('Seguranca e Auditoria', '1');
INSERT INTO CLASSES_STUDENTS VALUES('Seguranca e Auditoria', '2');
INSERT INTO CLASSES_STUDENTS VALUES('Seguranca e Auditoria', '3');
